# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ['tables']

highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Todd Hayton'
tagline:          'Freelance Software Developer'
description:      'Freelance Software Developer'
url:              http://toddhayton.com
baseurl:          

author:
  name:           'Todd Hayton'
  url:            http://toddhayton.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/thayton

gems:
  - jekyll-sitemap
